
# ARIMA model with Multiway communication between R and Python

##Loading reticulate R package to enable multiway communication between R and Python
```{r setting-r, warning=FALSE}
#Loading R packages
library(reticulate)
library(quantmod)
library(tidyverse)
#py_install("pandas")

```

## Loading needed Python pacakge
```{python setting-python}
# Loading Python library
import quandl
import warnings
import itertools
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from statsmodels.tsa.seasonal import seasonal_decompose
from datetime import datetime

# Loading custom function from Python Scripts. By doing this, We can achieve better program management
from arima_utils import ad_fuller_test, plot_rolling_stats
from arima_utils import plot_acf_pacf, arima_gridsearch_cv
```

## Processing data

```{r loading-data}
# loading data using R package quantmod
INTC <- getSymbols(Symbols = "INTC", src = "yahoo",  from = '2009-12-01',
           to = "2019-12-01", auto.assign = FALSE)
# class(INTC)
INTC_array <- Cl(INTC) 

# change index to first column
INTC_df <- tibble::rownames_to_column(
  Cl(INTC)%>% 
  as.data.frame(),
  "Date") %>% 
  rename( Value = "INTC.Close") %>% 
  mutate(
    Date = as.Date(Date)
  )
```

### Plotting with R
```{r plot-r}
plot(INTC_array)
```
# Plotting with Python
```{python}
#Directly Assign vlue of a r dataframe to a python dataframe
INTC_df_py =r.INTC_df


#datetime.strptime(INTC_df_py[[0]], '%m-%d-%Y').date()
INTC_df_py_new = INTC_df_py.set_index(INTC_df_py.columns[0])

INTC_df_py_new_reindex = INTC_df_py_new.reindex(pd.date_range(INTC_df_py_new.index.min(), INTC_df_py_new.index.max(), freq='D'))

```


```{python plot-python}
INTC_df_py_new_reindex.plot(figsize=(15, 6))
plt.show()
```

## Decompose

```{python}
                                  
decompose = seasonal_decompose(INTC_df_py_new_reindex.Value.interpolate())
decompose
```
## Dickey Fuller Test

### Original Series

```{python}
ad_fuller_test(INTC_df_py_new_reindex.Value)
plot_rolling_stats(INTC_df_py_new_reindex.Value).show()
```

### Log Series

```{python}
log_series = np.log(INTC_df_py_new_reindex.Value)

ad_fuller_test(log_series)
plot_rolling_stats(log_series)
```
### Log Difference
```{python}
# Using log series with a shift to make it stationary
log_series_shift = log_series - log_series.shift()
log_series_shift = log_series_shift[~np.isnan(log_series_shift)]
```

```{python}
ad_fuller_test(log_series_shift)
plot_rolling_stats(log_series_shift)

```

## ACF/ PACF

```{python}
plot_acf_pacf(log_series_shift)
```

## ARIMA

```{python}
INTC_df_py_new_reindex['log_series'] = log_series
INTC_df_py_new_reindex['log_series_shift'] = log_series_shift
```

### Training-Testing Split
```{python}
results_dict = arima_gridsearch_cv(INTC_df_py_new_reindex.log_series,cv_splits=5)
```

